In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from tree.mini_xgboost_classifier import MiniXGBoostClassifier
import pandas as pd
import os

In [ ]:
NHANES_dataset_path = "../datasets/NHANES"
# Sleep Disorders
SLQ_path = NHANES_dataset_path + "/SLQ_L.xpt"
# Demographic
DEMO_path = NHANES_dataset_path + "/DEMO_L.xpt"
# Vitamin D
VID_path = NHANES_dataset_path + "/VID_L.xpt"
# High-Sensitivity C-Reactive Protein
HSRCP_path = NHANES_dataset_path + "/HSRCP_L.xpt"
# Mental Health - Depression Screener
DPQ_path = NHANES_dataset_path + "/DPQ_L.xpt"

In [5]:
SLQ_df = pd.read_sas(SLQ_path)
SLQ_df.head()

       SEQN    SLQ300    SLQ310  SLD012    SLQ320    SLQ330  SLD013
0  130378.0  b'21:30'  b'07:00'     9.5  b'00:00'  b'09:00'     9.0
1  130379.0  b'21:00'  b'06:00'     9.0  b'21:00'  b'06:00'     9.0
2  130380.0  b'00:00'  b'08:00'     8.0  b'00:00'  b'09:00'     9.0
3  130384.0  b'21:30'  b'05:00'     7.5  b'23:00'  b'07:00'     8.0
4  130385.0  b'22:05'  b'06:15'     8.0  b'22:05'  b'06:15'     8.0

In [6]:
VID_df = pd.read_sas(VID_path)
VID_df.head()

,SEQN,WTPH2YR,LBXVIDMS,LBDVIDLC,LBXVD2MS,LBDVD2LC,LBXVD3MS,LBDVD3LC,LBXVE3MS,LBDVE3LC
0,130378.0,5.604213e+04,58.9,5.397605e-79,1.57,1.0,57.3,5.397605e-79,2.47,5.397605e-79
1,130379.0,3.743571e+04,60.5,5.397605e-79,1.57,1.0,58.9,5.397605e-79,3.40,5.397605e-79
2,130380.0,8.532884e+04,39.4,5.397605e-79,1.57,1.0,37.8,5.397605e-79,1.52,5.397605e-79
3,130381.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,5.963893e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
SLQ_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8501 entries, 0 to 8500
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SEQN    8501 non-null   float64
 1   SLQ300  8501 non-null   object
 2   SLQ310  8501 non-null   object
 3   SLD012  8388 non-null   float64
 4   SLQ320  8501 non-null   object
 5   SLQ330  8501 non-null   object
 6   SLD013  8387 non-null   float64
dtypes: float64(3), object(4)
memory usage: 465.0+ KB

In [7]:
VID_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8727 entries, 0 to 8726
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      8727 non-null   float64
 1   WTPH2YR   8727 non-null   float64
 2   LBXVIDMS  7307 non-null   float64
 3   LBDVIDLC  7307 non-null   float64
 4   LBXVD2MS  7307 non-null   float64
 5   LBDVD2LC  7307 non-null   float64
 6   LBXVD3MS  7308 non-null   float64
 7   LBDVD3LC  7308 non-null   float64
 8   LBXVE3MS  7238 non-null   float64
 9   LBDVE3LC  7238 non-null   float64
dtypes: float64(10)
memory usage: 681.9 KB