In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from sklearn.model_selection import train_test_split
import numpy as np
from xgboost import XGBClassifier
from tree.mini_xgboost_classifier import MiniXGBoostClassifier
from sklearn.metrics import accuracy_score
from tree.vectorized_single_hist_tree_boost import VectorizedSingleHistTreeBoost
from sklearn.datasets import make_classification
import shap
import matplotlib.pyplot as plt
import pandas as pd
from typing import Tuple
import polars as pl

/home/sakane/Documents/projects/python/mini_xgshap/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pl.read_parquet("../datasets/BRFSS/out.parquet")

In [3]:
df.head()

shape: (5, 20)
┌──────────┬─────┬────────┬────────┬───┬────────┬──────────┬───────────────────┬──────────────────┐
│ DIABETES ┆ SEX ┆ INCOME ┆ HIGHBP ┆ … ┆ SMOKER ┆ EXERCISE ┆ TOTAL_COMORBIDITY ┆ TOTAL_DISABILITY │
│ ---      ┆ --- ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---      ┆ ---               ┆ ---              │
│ u8       ┆ u8  ┆ u8     ┆ u8     ┆   ┆ u8     ┆ u8       ┆ u8                ┆ u8               │
╞══════════╪═════╪════════╪════════╪═══╪════════╪══════════╪═══════════════════╪══════════════════╡
│ 1        ┆ 2   ┆ null   ┆ 2      ┆ … ┆ 4      ┆ 2        ┆ 0                 ┆ 1                │
│ 3        ┆ 2   ┆ null   ┆ 2      ┆ … ┆ 4      ┆ 1        ┆ 2                 ┆ 1                │
│ 3        ┆ 2   ┆ 1      ┆ 2      ┆ … ┆ 3      ┆ 1        ┆ 2                 ┆ 3                │
│ 3        ┆ 2   ┆ null   ┆ 1      ┆ … ┆ 4      ┆ 1        ┆ 4                 ┆ 1                │
│ 1        ┆ 2   ┆ 5      ┆ 2      ┆ … ┆ 4      ┆ 1        ┆ 3                 ┆ 3                │
└──────────┴─────┴────────┴────────┴───┴────────┴──────────┴───────────────────┴──────────────────┘

In [5]:
df.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ DIABETES  ┆ SEX       ┆ INCOME    ┆ … ┆ SMOKER    ┆ EXERCISE  ┆ TOTAL_COM ┆ TOTAL_DI │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ORBIDITY  ┆ SABILITY │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.722563e ┆ 1.722287e ┆ 1.390882e ┆ … ┆ 1.638215e ┆ 1.665077e ┆ 1.722563e ┆ 1.722563 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 276.0     ┆ 331681.0  ┆ … ┆ 84348.0   ┆ 57486.0   ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2.748881  ┆ 1.538847  ┆ 3.93255   ┆ … ┆ 3.363602  ┆ 1.25932   ┆ 1.067932  ┆ 0.523397 │
│ std       ┆ 0.710784  ┆ 0.498489  ┆ 1.370112  ┆ … ┆ 0.9331    ┆ 0.438262  ┆ 1.233493  ┆ 0.992781 │
│ min       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 3.0       ┆ 1.0       ┆ 3.0       ┆ … ┆ 3.0       ┆ 1.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 3.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 4.0       ┆ 1.0       ┆ 1.0       ┆ 0.0      │
│ 75%       ┆ 3.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 4.0       ┆ 2.0       ┆ 2.0       ┆ 1.0      │
│ max       ┆ 4.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 4.0       ┆ 2.0       ┆ 9.0       ┆ 6.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
max_depth = 5
learning_rate = 0.1
n_estimators = 300
max_bin = 30
tree_method = 'hist'
gamma = 0
lb = 1